name: 'MS Teams Deployment Notification'
description: 'Sends a deployment notification to MS Teams using Adaptive Cards'
author: 'Yuriy Boev'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'message-circle'
  color: 'purple'

# Define your inputs here.
inputs:
  status:
    description: 'Deployment status'
    default: 'success'
    required: true
  last_sha:
    description: 'Last successful deploy commit SHA'
    required: false
  teams_webhook:
    description: 'Microsoft Teams webhook URL'
    required: true

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
